targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/features/**/domain/*.dart
            - lib/core/error/*.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/features/**/domain/*.dart
        options:
          explicit_to_json: true
