import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:nutriguide_mobile/features/meal_plan/domain/meal_plan_day.dart';

part 'weekly_meal_plan.freezed.dart';
part 'weekly_meal_plan.g.dart';

/// A 7-day meal plan starting on a Monday (AD-63).
///
/// Always normalized to start on a Monday — use [WeeklyMealPlan.create]
/// for construction to guarantee this invariant (spec MEAL-DOMAIN-002).
///
/// [isLocalFallback] is true when the plan was generated by the offline
/// local template algorithm rather than the AI Edge Function (AD-68).
@freezed
abstract class WeeklyMealPlan with _$WeeklyMealPlan {
  const WeeklyMealPlan._();

  const factory WeeklyMealPlan({
    required String id,
    required DateTime weekStartDate,
    @Default([]) List<MealPlanDay> days,
    @Default(false) bool isLocalFallback,
  }) = _WeeklyMealPlan;

  factory WeeklyMealPlan.fromJson(Map<String, dynamic> json) =>
      _$WeeklyMealPlanFromJson(json);

  /// Creates a [WeeklyMealPlan] with [weekStartDate] normalized to Monday.
  ///
  /// Any day of the week can be passed — the factory subtracts
  /// `weekday - 1` days (Monday = 1, so Monday subtracts 0).
  /// The time component is also stripped so equality comparisons work
  /// against date-only values.
  factory WeeklyMealPlan.create({
    required String id,
    required DateTime weekStartDate,
    List<MealPlanDay> days = const [],
    bool isLocalFallback = false,
  }) {
    // ISO weekday: Monday = 1, ..., Sunday = 7
    final monday = weekStartDate.subtract(
      Duration(days: weekStartDate.weekday - 1),
    );
    // Strip time component
    final mondayDateOnly = DateTime(monday.year, monday.month, monday.day);

    return WeeklyMealPlan(
      id: id,
      weekStartDate: mondayDateOnly,
      days: days,
      isLocalFallback: isLocalFallback,
    );
  }

  /// Returns the [MealPlanDay] for [date], or null if not found.
  ///
  /// Comparison ignores the time component so that DateTime objects
  /// from different sources (e.g., route params, Supabase responses)
  /// match correctly.
  MealPlanDay? dayFor(DateTime date) {
    final target = DateTime(date.year, date.month, date.day);
    for (final day in days) {
      final d = DateTime(day.date.year, day.date.month, day.date.day);
      if (d == target) return day;
    }
    return null;
  }
}
